# Generated by Django 5.2.4 on 2025-07-11 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('razza', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('data_ingresso', models.DateField(default=django.utils.timezone.now)),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('microchip', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('sterilizzato', models.BooleanField(default=False)),
                ('descrizione', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disponibile', 'Disponibile per adozione'), ('in_adozione', 'In processo di adozione'), ('adottato', 'Adottato'), ('in_cura', 'In cura'), ('non_adottabile', 'Non adottabile')], default='disponibile', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cani_foto/')),
            ],
            options={
                'verbose_name_plural': 'Cani',
            },
        ),
        migrations.CreateModel(
            name='Canile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('capacita_massima', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Canili',
            },
        ),
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('passeggiata', 'Passeggiata'), ('gioco', 'Sessione di gioco'), ('addestramento', 'Addestramento'), ('visita', 'Visita potenziale adottante'), ('altro', 'Altro')], max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attivita_svolte', to=settings.AUTH_USER_MODEL)),
                ('cane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to='GestioneCanile.cane')),
            ],
            options={
                'verbose_name_plural': 'Attività',
                'ordering': ['-data', '-ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Adozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adottante_nome', models.CharField(max_length=100)),
                ('adottante_cognome', models.CharField(max_length=100)),
                ('adottante_email', models.EmailField(max_length=254)),
                ('adottante_telefono', models.CharField(max_length=20)),
                ('adottante_indirizzo', models.CharField(max_length=200)),
                ('data_richiesta', models.DateField(default=django.utils.timezone.now)),
                ('data_adozione', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('richiesta', 'Richiesta'), ('in_valutazione', 'In valutazione'), ('approvata', 'Approvata'), ('completata', 'Completata'), ('rifiutata', 'Rifiutata')], default='richiesta', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adozioni_gestite', to=settings.AUTH_USER_MODEL)),
                ('cane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adozioni', to='GestioneCanile.cane')),
            ],
            options={
                'verbose_name_plural': 'Adozioni',
                'ordering': ['-data_richiesta'],
            },
        ),
        migrations.AddField(
            model_name='cane',
            name='canile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cani', to='GestioneCanile.canile'),
        ),
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo_intervento', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('veterinario', models.CharField(max_length=100)),
                ('farmaci_prescritti', models.TextField(blank=True)),
                ('prossimo_controllo', models.DateField(blank=True, null=True)),
                ('cane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registri_sanitari', to='GestioneCanile.cane')),
            ],
            options={
                'verbose_name_plural': 'Registri Sanitari',
                'ordering': ['-data'],
            },
        ),
    ]
