# Generated by Django 5.2.4 on 2025-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestioneCanile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cane',
            name='compatibile_animali',
            field=models.BooleanField(default=True, help_text='Compatibile con altri animali'),
        ),
        migrations.AddField(
            model_name='cane',
            name='compatibile_bambini',
            field=models.BooleanField(default=True, help_text='Compatibile con bambini'),
        ),
        migrations.AddField(
            model_name='cane',
            name='taglia',
            field=models.CharField(blank=True, choices=[('piccola', 'Piccola'), ('media', 'Media'), ('grande', 'Grande'), ('molto_grande', 'Molto grande')], max_length=20, null=True),
        ),
    ]
