# Generated by Django 5.2.4 on 2025-07-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestioneCanile', '0002_cane_compatibile_animali_cane_compatibile_bambini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adozione',
            name='accetta_termini',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adozione',
            name='descrizione_altri_animali',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adozione',
            name='esperienza_animali',
            field=models.CharField(choices=[('nessuna', 'Nessuna esperienza precedente'), ('poca', 'Poca esperienza'), ('media', 'Media esperienza'), ('molta', 'Molta esperienza')], default='nessuna', max_length=20),
        ),
        migrations.AddField(
            model_name='adozione',
            name='presenza_altri_animali',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adozione',
            name='presenza_bambini',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adozione',
            name='ricevi_aggiornamenti_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adozione',
            name='ricevi_aggiornamenti_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adozione',
            name='tipo_abitazione',
            field=models.CharField(choices=[('appartamento', 'Appartamento'), ('casa_giardino', 'Casa con giardino'), ('casa_rurale', 'Casa rurale/fattoria'), ('altro', 'Altro')], default='appartamento', max_length=20),
        ),
    ]
