# Generated by Django 5.2.4 on 2025-07-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestioneCanile', '0003_adozione_accetta_termini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adozione',
            name='codice_tracciamento',
            field=models.CharField(blank=True, help_text='Codice univoco per tracciare la richiesta di adozione', max_length=10, null=True, unique=True),
        ),
    ]
